import type { Card } from '../../types';

export const CARD_DEFINITIONS: Card[] = [
  {
    id: 'meme-cannon',
    name: 'Meme Cannon',
    type: 'attack',
    description: 'Drops a goofy meme image over the board with your last wrong guess as caption.',
    targetSelf: false,
    duration: 'instant',
  },
  {
    id: 'brainrot-glitch',
    name: 'Brainrot Glitch',
    type: 'attack',
    description: "Glitch-shakes the target's letter tiles for one guess cycle.",
    targetSelf: false,
    duration: 'instant',
  },
  {
    id: 'status-dog',
    name: 'Status Dog',
    type: 'attack',
    description: "A loyal pup covers one of the target's revealed letters for 10 seconds.",
    targetSelf: false,
    duration: 'persistent',
  },
  {
    id: 'playful-insult',
    name: 'Playful Insult',
    type: 'attack',
    description: 'A playful jab pops up in front of the target.',
    targetSelf: false,
    duration: 'instant',
  },
  {
    id: 'forced-break',
    name: 'Forced Break',
    type: 'attack',
    description: 'Opens a popup the target must manually dismiss.',
    targetSelf: false,
    duration: 'instant',
  },
  {
    id: 'bored-distraction',
    name: 'Bored Distraction',
    type: 'attack',
    description: 'A corner distraction popup with a random activity suggestion.',
    targetSelf: false,
    duration: 'instant',
  },
  {
    id: 'recipe-spam',
    name: 'Recipe Spam',
    type: 'attack',
    description: 'Overlays a food-blog style scrolling ingredient list.',
    targetSelf: false,
    duration: 'instant',
  },
  {
    id: 'rejection-letter',
    name: 'Rejection Letter',
    type: 'attack',
    description: 'A formal rejection email overlay for your guess.',
    targetSelf: false,
    duration: 'instant',
  },
  {
    id: 'face-swap-glitch',
    name: 'Face Swap Glitch',
    type: 'attack',
    description: 'Triggers a cartoon face-swap on the surfer for 5 seconds.',
    targetSelf: false,
    duration: 'instant',
  },
  {
    id: 'letter-reveal',
    name: 'Letter Reveal',
    type: 'buff',
    description: 'Reveals one letter in the answer at its correct position.',
    targetSelf: true,
    duration: 'instant',
  },
  {
    id: 'cosmic-reset',
    name: 'Cosmic Reset',
    type: 'buff',
    description: 'Removes your most recent wrong guess from the board.',
    targetSelf: true,
    duration: 'instant',
  },
  {
    id: 'marine-hint',
    name: 'Marine Hint',
    type: 'buff',
    description: 'Tells you how many vowels are in the answer.',
    targetSelf: true,
    duration: 'instant',
  },
  {
    id: 'tide-whisper',
    name: 'Tide Whisper',
    type: 'buff',
    description: 'Reveals the first or last letter of the answer.',
    targetSelf: true,
    duration: 'instant',
  },
  {
    id: 'forecast',
    name: 'Forecast',
    type: 'buff',
    description: 'Reveals whether a random position is a vowel or consonant.',
    targetSelf: true,
    duration: 'instant',
  },
  {
    id: 'related-current',
    name: 'Related Current',
    type: 'buff',
    description: 'Reveals a thematically related word to the answer.',
    targetSelf: true,
    duration: 'instant',
  },
  {
    id: 'resume-polish',
    name: 'Resume Polish',
    type: 'buff',
    description: 'Suggests an optimal next guess based on your current guesses.',
    targetSelf: true,
    duration: 'instant',
  },
  {
    id: 'chess-gambit',
    name: 'Chess Gambit',
    type: 'wildcard',
    description: 'Both players must solve a mini chess puzzle before continuing.',
    targetSelf: false,
    duration: 'instant',
  },
  {
    id: 'dice-roll',
    name: 'Dice Roll',
    type: 'wildcard',
    description: 'Randomizes or swaps the next card draw for both players.',
    targetSelf: false,
    duration: 'instant',
  },
  {
    id: 'beach-playlist',
    name: 'Beach Playlist',
    type: 'wildcard',
    description: 'Swaps the beach playlist for 30 seconds.',
    targetSelf: false,
    duration: 'instant',
  },
  {
    id: 'critics-rating',
    name: "Critic's Rating",
    type: 'wildcard',
    description: 'Rates guess efficiency at round end; winner gets a bonus.',
    targetSelf: false,
    duration: 'instant',
  },
];

export function getCardById(id: string): Card | undefined {
  return CARD_DEFINITIONS.find((c) => c.id === id);
}
