import type { Card } from '../../types';

export const CARD_DEFINITIONS: Card[] = [
  {
    id: 'meme-overlay',
    name: 'Meme Overlay',
    type: 'attack',
    description: 'Drops a goofy meme image over the opponent board briefly.',
    targetSelf: false,
    duration: 'instant',
  },
  {
    id: 'insult-popup',
    name: 'Insult Popup',
    type: 'attack',
    description: 'A playful jab pops up in front of the opponent.',
    targetSelf: false,
    duration: 'instant',
  },
  {
    id: 'status-dog',
    name: 'Status Dog',
    type: 'attack',
    description: "A loyal pup sits on one of the opponent's revealed letters, covering it.",
    targetSelf: false,
    duration: 'persistent',
  },
  {
    id: 'brainrot-jitter',
    name: 'Brainrot Jitter',
    type: 'attack',
    description: "Shakes the opponent's UI for a few seconds.",
    targetSelf: false,
    duration: 'instant',
  },
  {
    id: 'forced-break',
    name: 'Forced Break',
    type: 'attack',
    description: 'Opens a popup the opponent must manually dismiss.',
    targetSelf: false,
    duration: 'instant',
  },
  {
    id: 'bored-suggestion',
    name: 'Bored Suggestion',
    type: 'attack',
    description: 'A "you might also like..." distraction popup.',
    targetSelf: false,
    duration: 'instant',
  },
  {
    id: 'related-word-hint',
    name: 'Related Word Hint',
    type: 'buff',
    description: 'Reveals a thematic hint related to the answer.',
    targetSelf: true,
    duration: 'instant',
  },
  {
    id: 'letter-reveal',
    name: 'Letter Reveal',
    type: 'buff',
    description: 'Reveals one letter in the answer at its correct position.',
    targetSelf: true,
    duration: 'instant',
  },
  {
    id: 'guess-eraser',
    name: 'Guess Eraser',
    type: 'buff',
    description: 'Removes one wrong guess from your board.',
    targetSelf: true,
    duration: 'instant',
  },
  {
    id: 'vowel-count',
    name: 'Vowel Count',
    type: 'buff',
    description: 'Tells you how many vowels are in the answer.',
    targetSelf: true,
    duration: 'instant',
  },
  {
    id: 'chess-puzzle',
    name: 'Chess Puzzle',
    type: 'wildcard',
    description: 'Both players must solve a quick chess puzzle before continuing.',
    targetSelf: false,
    duration: 'instant',
  },
  {
    id: 'dice-reroll',
    name: 'Dice Reroll',
    type: 'wildcard',
    description: 'Randomizes the next card draw for both players.',
    targetSelf: false,
    duration: 'instant',
  },
];
