import { getAllWords } from './wordList';

/** Hand-curated related words; getRelatedHint falls back for any missing entry. */
const CURATED: Record<string, string> = {
  SAND: 'dune',
  SURF: 'wave',
  WAVE: 'swell',
  TIDE: 'ebb',
  SHELL: 'clam',
  CRAB: 'lobster',
  REEF: 'coral',
  CORAL: 'reef',
  SHORE: 'coast',
  DUNE: 'sand',
  BEACH: 'shore',
  SALT: 'brine',
  KELP: 'seaweed',
  BUOY: 'marker',
  BOAT: 'sail',
  SHARK: 'fish',
  SAIL: 'wind',
  SWIM: 'float',
  FOAM: 'surf',
  PALM: 'tropical',
  OCEAN: 'sea',
  PIER: 'dock',
  ROCK: 'stone',
  FISH: 'swim',
  SUN: 'warmth',
  TOWEL: 'dry',
  WETSUIT: 'dive',
  LIFEGUARD: 'rescue',
  BAY: 'inlet',
  COAST: 'shore',
  GULF: 'bay',
  COVE: 'inlet',
  DOCK: 'pier',
  LAGOON: 'bay',
  WHALE: 'mammal',
  DOLPHIN: 'porpoise',
  SEAL: 'pup',
  GULL: 'bird',
  SWELL: 'wave',
  CURRENT: 'flow',
  ISLAND: 'atoll',
  DRIFTWOOD: 'wreck',
  SEAWEED: 'kelp',
  SUNSET: 'dusk',
  HORIZON: 'skyline',
  TROPICAL: 'warm',
  VOYAGE: 'sail',
  MARINA: 'harbor',
  HARBOR: 'port',
  LIGHTHOUSE: 'beacon',
  SNORKEL: 'dive',
  KAYAK: 'paddle',
  YACHT: 'boat',
  UMBRELLA: 'shade',
  HAMMOCK: 'rest',
  MUSSEL: 'clam',
  CLAM: 'shell',
  SQUID: 'octopus',
  OTTER: 'seal',
  TERN: 'gull',
  PELICAN: 'bird',
  HERON: 'egret',
  SANDBAR: 'shore',
  BREAKER: 'wave',
  RIP: 'current',
  EBB: 'tide',
  FLOOD: 'tide',
  ESTUARY: 'marsh',
  MARSH: 'wetland',
  MANGROVE: 'swamp',
  ATOLL: 'reef',
  ARCHIPELAGO: 'islands',
  PENINSULA: 'coast',
  HEADLAND: 'cliff',
  CLIFF: 'bluff',
  BLUFF: 'cliff',
  DUNEGRASS: 'dune',
  SEAGRASS: 'kelp',
  ANEMONE: 'coral',
  STARFISH: 'sea star',
  URCHIN: 'spine',
  LOBSTER: 'crab',
  SHRIMP: 'prawn',
  OYSTER: 'pearl',
  SCALLOP: 'shell',
  ABALONE: 'mollusk',
  NAUTILUS: 'shell',
  BARNACLE: 'crust',
  PLANKTON: 'microbe',
  JELLYFISH: 'sting',
  MANATEE: 'dugong',
  NARWHAL: 'tusk',
  PORPOISE: 'dolphin',
  ALBATROSS: 'seabird',
  FRIGATE: 'bird',
  CORMORANT: 'diver',
  SANDCASTLE: 'beach',
  SUNSCREEN: 'lotion',
  FLIPFLOP: 'sandal',
  PADDLE: 'oar',
  CANOE: 'boat',
  CATAMARAN: 'yacht',
  ANCHORAGE: 'mooring',
  MOORING: 'dock',
  BEACON: 'light',
  SIGNAL: 'flag',
  WRACK: 'debris',
  FLOTSAM: 'jetsam',
  JETSAM: 'flotsam',
  SHIPWRECK: 'wreck',
  TREASURE: 'gold',
  PARASOL: 'umbrella',
  COOLER: 'ice',
  PICNIC: 'lunch',
  BARBECUE: 'grill',
  BONFIRE: 'flame',
  CAMPFIRE: 'bonfire',
  SUNRISE: 'dawn',
  SEABREEZE: 'wind',
  SALTWATER: 'ocean',
  FRESHWATER: 'spring',
  BRACKISH: 'estuary',
  SUBTROPICAL: 'tropical',
  EQUATOR: 'latitude',
  LATITUDE: 'parallel',
  LONGITUDE: 'meridian',
  NAUTICAL: 'maritime',
  MARITIME: 'nautical',
  SEAFARING: 'sailing',
  EXPEDITION: 'voyage',
  HARP: 'harp seal',
};

export function getRelatedHint(answer: string): string {
  const upper = answer.toUpperCase();
  if (CURATED[upper]) return CURATED[upper];

  const words = getAllWords();
  const others = words.filter((w) => w !== upper);
  const sameStart = others.find((w) => w[0] === upper[0] && w.length >= 4);
  if (sameStart) return sameStart.toLowerCase();

  const sharesBigram = others.find((w) => {
    for (let i = 0; i < upper.length - 1; i++) {
      const bg = upper.slice(i, i + 2);
      if (w.includes(bg)) return true;
    }
    return false;
  });
  if (sharesBigram) return sharesBigram.toLowerCase();

  return 'coastal vibe';
}

export const RELATED_HINTS = CURATED;
